FROM golang:1.25.1-alpine3.22 AS builder

WORKDIR /app
RUN apk add --no-cache protobuf
COPY go.mod go.sum ./
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

RUN go mod download
COPY . .
RUN protoc --go_out=. --go_opt=paths=source_relative ./domain/protobuf/*.proto
RUN go build -ldflags="-s -w" -o ./bin/server .

FROM scratch
COPY --from=builder /app/bin/server /server
ENV GIN_MODE=release
CMD [ "/server" ]