version: '3.8'

services:
  backend:
    image: rakaoran/gto-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_KEY=${JWT_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    stop_grace_period: 1h
    networks:
      - gto-net

  postgres:
    image: postgres:16-alpine3.22
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - gto-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    deploy:
      restart_policy:
        condition: any
    networks:
      - gto-net

    
volumes:
  pg_data:
networks:
  gto-net:
    driver: overlay