FROM golang:1.25.1-alpine3.22

WORKDIR /app

RUN go install github.com/air-verse/air@latest

RUN air init
COPY .air.toml .
COPY go.mod go.sum ./

RUN go mod download

COPY . .
ENV GIN_MODE=debug

CMD [ "air" ]