FROM golang:1.25.1-alpine3.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY . .
RUN go build -ldflags="-s -w" -o ./bin/server .

FROM scratch
COPY --from=builder /app/bin/server /server
ENV GIN_MODE=release
CMD [ "/server" ]