// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/internal/game/serialization.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// NEW: Single drawing path with Fabric.js data
type DrawingPath struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PathData       string                 `protobuf:"bytes,1,opt,name=pathData,proto3" json:"pathData,omitempty"`             // SVG path data (d attribute)
	Stroke         string                 `protobuf:"bytes,2,opt,name=stroke,proto3" json:"stroke,omitempty"`                 // Color
	StrokeWidth    int32                  `protobuf:"varint,3,opt,name=strokeWidth,proto3" json:"strokeWidth,omitempty"`      // Line width
	StrokeLineCap  string                 `protobuf:"bytes,4,opt,name=strokeLineCap,proto3" json:"strokeLineCap,omitempty"`   // Line cap style
	StrokeLineJoin string                 `protobuf:"bytes,5,opt,name=strokeLineJoin,proto3" json:"strokeLineJoin,omitempty"` // Line join style
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrawingPath) Reset() {
	*x = DrawingPath{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawingPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawingPath) ProtoMessage() {}

func (x *DrawingPath) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawingPath.ProtoReflect.Descriptor instead.
func (*DrawingPath) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{2}
}

func (x *DrawingPath) GetPathData() string {
	if x != nil {
		return x.PathData
	}
	return ""
}

func (x *DrawingPath) GetStroke() string {
	if x != nil {
		return x.Stroke
	}
	return ""
}

func (x *DrawingPath) GetStrokeWidth() int32 {
	if x != nil {
		return x.StrokeWidth
	}
	return 0
}

func (x *DrawingPath) GetStrokeLineCap() string {
	if x != nil {
		return x.StrokeLineCap
	}
	return ""
}

func (x *DrawingPath) GetStrokeLineJoin() string {
	if x != nil {
		return x.StrokeLineJoin
	}
	return ""
}

// NEW: Clear canvas command
type ClearCanvas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clear         bool                   `protobuf:"varint,1,opt,name=clear,proto3" json:"clear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCanvas) Reset() {
	*x = ClearCanvas{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCanvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCanvas) ProtoMessage() {}

func (x *ClearCanvas) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCanvas.ProtoReflect.Descriptor instead.
func (*ClearCanvas) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{3}
}

func (x *ClearCanvas) GetClear() bool {
	if x != nil {
		return x.Clear
	}
	return false
}

type WordChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordIndex     int32                  `protobuf:"varint,1,opt,name=wordIndex,proto3" json:"wordIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordChoice) Reset() {
	*x = WordChoice{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordChoice) ProtoMessage() {}

func (x *WordChoice) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordChoice.ProtoReflect.Descriptor instead.
func (*WordChoice) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{4}
}

func (x *WordChoice) GetWordIndex() int32 {
	if x != nil {
		return x.WordIndex
	}
	return 0
}

type TurnSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	Scores        []int32                `protobuf:"varint,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnSummary) Reset() {
	*x = TurnSummary{}
	mi := &file_api_internal_game_serialization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnSummary) ProtoMessage() {}

func (x *TurnSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_game_serialization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnSummary.ProtoReflect.Descriptor instead.
func (*TurnSummary) Descriptor() ([]byte, []int) {
	return file_api_internal_game_serialization_proto_rawDescGZIP(), []int{5}
}

func (x *TurnSummary) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *TurnSummary) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_api_internal_game_serialization_proto protoreflect.FileDescriptor

const file_api_internal_game_serialization_proto_rawDesc = "" +
	"\n" +
	"%api/internal/game/serialization.proto\x12\x04game\"/\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb1\x01\n" +
	"\vDrawingPath\x12\x1a\n" +
	"\bpathData\x18\x01 \x01(\tR\bpathData\x12\x16\n" +
	"\x06stroke\x18\x02 \x01(\tR\x06stroke\x12 \n" +
	"\vstrokeWidth\x18\x03 \x01(\x05R\vstrokeWidth\x12$\n" +
	"\rstrokeLineCap\x18\x04 \x01(\tR\rstrokeLineCap\x12&\n" +
	"\x0estrokeLineJoin\x18\x05 \x01(\tR\x0estrokeLineJoin\"#\n" +
	"\vClearCanvas\x12\x14\n" +
	"\x05clear\x18\x01 \x01(\bR\x05clear\"*\n" +
	"\n" +
	"WordChoice\x12\x1c\n" +
	"\twordIndex\x18\x01 \x01(\x05R\twordIndex\"C\n" +
	"\vTurnSummary\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x05R\x06scoresB\x18Z\x16api/internal/game;gameb\x06proto3"

var (
	file_api_internal_game_serialization_proto_rawDescOnce sync.Once
	file_api_internal_game_serialization_proto_rawDescData []byte
)

func file_api_internal_game_serialization_proto_rawDescGZIP() []byte {
	file_api_internal_game_serialization_proto_rawDescOnce.Do(func() {
		file_api_internal_game_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_internal_game_serialization_proto_rawDesc), len(file_api_internal_game_serialization_proto_rawDesc)))
	})
	return file_api_internal_game_serialization_proto_rawDescData
}

var file_api_internal_game_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_internal_game_serialization_proto_goTypes = []any{
	(*Event)(nil),       // 0: game.Event
	(*Message)(nil),     // 1: game.Message
	(*DrawingPath)(nil), // 2: game.DrawingPath
	(*ClearCanvas)(nil), // 3: game.ClearCanvas
	(*WordChoice)(nil),  // 4: game.WordChoice
	(*TurnSummary)(nil), // 5: game.TurnSummary
}
var file_api_internal_game_serialization_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_internal_game_serialization_proto_init() }
func file_api_internal_game_serialization_proto_init() {
	if File_api_internal_game_serialization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_internal_game_serialization_proto_rawDesc), len(file_api_internal_game_serialization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_internal_game_serialization_proto_goTypes,
		DependencyIndexes: file_api_internal_game_serialization_proto_depIdxs,
		MessageInfos:      file_api_internal_game_serialization_proto_msgTypes,
	}.Build()
	File_api_internal_game_serialization_proto = out.File
	file_api_internal_game_serialization_proto_goTypes = nil
	file_api_internal_game_serialization_proto_depIdxs = nil
}
