-- +goose Up
-- +goose StatementBegin
INSERT INTO words (word) VALUES
    ('penguin'),
    ('giraffe'),
    ('dolphin'),
    ('volcano'),
    ('rainbow'),
    ('castle'),
    ('pirate'),
    ('spaceship'),
    ('dragon'),
    ('lighthouse'),
    ('snowman'),
    ('guitar'),
    ('umbrella'),
    ('flamingo'),
    ('tornado'),
    ('trophy'),
    ('rocket'),
    ('octopus'),
    ('pineapple'),
    ('hamburger'),
    ('house'),
    ('airplane'),
    ('shark'),
    ('crown'),
    ('palm tree'),
    ('dinosaur'),
    ('guitar'),
    ('pizza'),
    ('sun'),
    ('moon'),
    ('star'),
    ('heart'),
    ('fish'),
    ('frog'),
    ('bear'),
    ('lion'),
    ('zebra'),
    ('parrot'),
    ('monkey'),
    ('snake'),
    ('eagle'),
    ('whale'),
    ('turtle'),
    ('crab'),
    ('spider'),
    ('butterfly'),
    ('bee'),
    ('ladybug'),
    ('mushroom'),
    ('tree'),
    ('flower'),
    ('mountain'),
    ('ocean'),
    ('island'),
    ('bridge'),
    ('train'),
    ('boat'),
    ('car'),
    ('truck'),
    ('bus'),
    ('helicopter'),
    ('balloon'),
    ('kite'),
    ('sailboat'),
    ('canoe'),
    ('surfboard'),
    ('skateboard'),
    ('snowboard'),
    ('sled'),
    ('igloo'),
    ('tent'),
    ('cabin'),
    ('pyramid'),
    ('statue'),
    ('clock'),
    ('mirror'),
    ('candle'),
    ('lantern'),
    ('lamp'),
    ('book'),
    ('pencil'),
    ('camera'),
    ('television'),
    ('phone'),
    ('computer'),
    ('keyboard'),
    ('drum'),
    ('piano'),
    ('violin'),
    ('trumpet'),
    ('saxophone'),
    ('microphone'),
    ('headphones'),
    ('trophy'),
    ('medal'),
    ('flag'),
    ('compass'),
    ('anchor'),
    ('treasure chest'),
    ('sword'),
    ('shield'),
    ('helmet'),
    ('arrow'),
    ('bow'),
    ('cannon'),
    ('bomb'),
    ('fireworks'),
    ('campfire'),
    ('log'),
    ('rock'),
    ('diamond'),
    ('gold coin'),
    ('ring'),
    ('necklace'),
    ('hat'),
    ('scarf'),
    ('boots'),
    ('gloves'),
    ('sunglasses'),
    ('backpack'),
    ('suitcase'),
    ('purse'),
    ('basket'),
    ('bucket'),
    ('cup'),
    ('bowl'),
    ('plate'),
    ('fork'),
    ('knife'),
    ('spoon'),
    ('bottle'),
    ('glass'),
    ('jar'),
    ('box'),
    ('bag'),
    ('envelope'),
    ('letter'),
    ('newspaper'),
    ('map'),
    ('globe'),
    ('flag'),
    ('clock tower'),
    ('roller coaster'),
    ('carousel'),
    ('swing'),
    ('slide'),
    ('seesaw'),
    ('sandbox'),
    ('snowflake'),
    ('cloud'),
    ('lightning'),
    ('raindrop'),
    ('leaf'),
    ('acorn'),
    ('pumpkin'),
    ('apple'),
    ('cherry'),
    ('grape'),
    ('watermelon'),
    ('strawberry'),
    ('orange'),
    ('lemon'),
    ('coconut'),
    ('corn'),
    ('carrot'),
    ('potato'),
    ('tomato'),
    ('broccoli'),
    ('onion'),
    ('pepper'),
    ('garlic'),
    ('bread'),
    ('cake'),
    ('cookie'),
    ('donut'),
    ('ice cream'),
    ('candy'),
    ('chocolate'),
    ('popcorn'),
    ('hot dog'),
    ('french fries'),
    ('taco'),
    ('sushi'),
    ('egg'),
    ('bacon'),
    ('cheese'),
    ('butter'),
    ('milk'),
    ('coffee'),
    ('tea'),
    ('juice'),
    ('soda'),
    ('wine'),
    ('beer'),
    ('cocktail'),
    ('smoothie'),
    ('soup'),
    ('salad'),
    ('sandwich'),
    ('pasta'),
    ('rice'),
    ('noodles'),
    ('chicken'),
    ('fish stick'),
    ('lobster'),
    ('shrimp'),
    ('oyster'),
    ('snail'),
    ('ant'),
    ('cricket'),
    ('firefly'),
    ('dragonfly'),
    ('mosquito'),
    ('fly'),
    ('worm'),
    ('caterpillar'),
    ('cocoon'),
    ('nest'),
    ('egg'),
    ('feather'),
    ('wing'),
    ('tail'),
    ('paw'),
    ('claw'),
    ('horn'),
    ('hoof'),
    ('fin'),
    ('shell'),
    ('bone'),
    ('skull'),
    ('ghost'),
    ('alien'),
    ('robot'),
    ('wizard'),
    ('witch'),
    ('vampire'),
    ('zombie'),
    ('mummy'),
    ('skeleton'),
    ('clown'),
    ('cowboy'),
    ('astronaut'),
    ('firefighter'),
    ('police officer'),
    ('doctor'),
    ('chef'),
    ('sailor'),
    ('knight'),
    ('princess'),
    ('king'),
    ('queen'),
    ('angel'),
    ('devil'),
    ('santa claus'),
    ('elf'),
    ('tooth fairy'),
    ('mermaid'),
    ('unicorn'),
    ('phoenix'),
    ('griffin'),
    ('kraken'),
    ('werewolf'),
    ('cyclops'),
    ('sphinx'),
    ('yeti'),
    ('bigfoot'),
    ('batman'),
    ('superman'),
    ('spider-man'),
    ('iron man'),
    ('captain america'),
    ('wonder woman'),
    ('thor'),
    ('hulk'),
    ('wolverine'),
    ('Mickey Mouse'),
    ('Spongebob'),
    ('Pikachu'),
    ('Pac-Man'),
    ('Mario'),
    ('Luigi'),
    ('Scooby-Doo'),
    ('Bugs Bunny'),
    ('Donald Duck'),
    ('Goofy'),
    ('Elsa'),
    ('Simba'),
    ('Nemo'),
    ('Shrek'),
    ('Winnie the Pooh'),
    ('Darth Vader'),
    ('Yoda'),
    ('Frankenstein'),
    ('Dracula'),
    ('football'),
    ('basketball'),
    ('baseball'),
    ('soccer ball'),
    ('tennis racket'),
    ('golf club'),
    ('pool table'),
    ('bowling pin'),
    ('dart'),
    ('chess'),
    ('dice'),
    ('cards'),
    ('puzzle'),
    ('yo-yo'),
    ('frisbee'),
    ('boomerang'),
    ('fishing rod'),
    ('magnifying glass'),
    ('telescope'),
    ('microscope'),
    ('thermometer'),
    ('hourglass'),
    ('stopwatch'),
    ('battery'),
    ('lightbulb'),
    ('magnet'),
    ('scissors'),
    ('stapler'),
    ('tape'),
    ('glue'),
    ('paint brush'),
    ('crayon'),
    ('eraser'),
    ('ruler'),
    ('protractor'),
    ('calculator'),
    ('abacus'),
    ('coin'),
    ('dollar bill'),
    ('wallet'),
    ('key'),
    ('lock'),
    ('door'),
    ('window'),
    ('stairs'),
    ('ladder'),
    ('fence'),
    ('wall'),
    ('roof'),
    ('chimney'),
    ('garage'),
    ('barn'),
    ('church'),
    ('school'),
    ('hospital'),
    ('library'),
    ('museum'),
    ('stadium'),
    ('theater'),
    ('cinema'),
    ('zoo'),
    ('farm'),
    ('garden'),
    ('forest'),
    ('desert'),
    ('beach'),
    ('cliff'),
    ('cave'),
    ('canyon'),
    ('river'),
    ('waterfall'),
    ('lake'),
    ('pond'),
    ('swamp'),
    ('jungle'),
    ('meadow'),
    ('field'),
    ('highway'),
    ('street'),
    ('alley'),
    ('tunnel'),
    ('dam'),
    ('well'),
    ('fountain'),
    ('pool'),
    ('bathtub'),
    ('shower'),
    ('toilet'),
    ('sink'),
    ('faucet'),
    ('pipe'),
    ('chimney'),
    ('fireplace'),
    ('oven'),
    ('stove'),
    ('fridge'),
    ('microwave'),
    ('toaster'),
    ('blender'),
    ('vacuum'),
    ('broom'),
    ('mop'),
    ('trash can'),
    ('mailbox'),
    ('street sign'),
    ('traffic light'),
    ('stop sign'),
    ('fire hydrant'),
    ('bench'),
    ('table'),
    ('chair'),
    ('couch'),
    ('bed'),
    ('pillow'),
    ('blanket'),
    ('dresser'),
    ('bookshelf'),
    ('desk'),
    ('lamp'),
    ('curtain'),
    ('rug'),
    ('shelf'),
    ('cupboard'),
    ('drawer'),
    ('cabinet'),
    ('attic'),
    ('basement'),
    ('garage'),
    ('shed'),
    ('treehouse'),
    ('birdhouse'),
    ('doghouse'),
    ('scarecrow'),
    ('windmill'),
    ('well'),
    ('totem pole'),
    ('statue of liberty'),
    ('eiffel tower'),
    ('big ben'),
    ('wall'),
    ('hollywood'),
    ('canyon'),
    ('eclipse'),
    ('comet'),
    ('saturn'),
    ('mars'),
    ('jupiter'),
    ('black hole'),
    ('nebula'),
    ('constellation'),
    ('milky way'),
    ('earth'),
    ('mars rover'),
    ('satellite'),
    ('space station'),
    ('meteor'),
    ('supernova')
ON CONFLICT (word) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
