// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: domain/protobuf/protocol.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerPacket_DrawingData
	//	*ServerPacket_PlayerJoined_
	//	*ServerPacket_GameStarted_
	//	*ServerPacket_RoundUpdate_
	//	*ServerPacket_PlayerIsChoosingWord_
	//	*ServerPacket_PlayerIsDrawing_
	//	*ServerPacket_TurnSummary_
	//	*ServerPacket_PlayerGuessedTheWord_
	//	*ServerPacket_Leaderboard
	//	*ServerPacket_PlayerMessage_
	//	*ServerPacket_PleaseChooseAWord_
	//	*ServerPacket_InitialRoomSnapshot_
	//	*ServerPacket_YourTurnToDraw_
	//	*ServerPacket_PlayerLeft_
	Payload         isServerPacket_Payload `protobuf_oneof:"payload"`
	ServerTimestamp int64                  `protobuf:"varint,16,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerPacket) GetPayload() isServerPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerPacket) GetDrawingData() *DrawingData {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_DrawingData); ok {
			return x.DrawingData
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerJoined() *ServerPacket_PlayerJoined {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerJoined_); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *ServerPacket) GetGameStarted() *ServerPacket_GameStarted {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_GameStarted_); ok {
			return x.GameStarted
		}
	}
	return nil
}

func (x *ServerPacket) GetRoundUpdate() *ServerPacket_RoundUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_RoundUpdate_); ok {
			return x.RoundUpdate
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerIsChoosingWord() *ServerPacket_PlayerIsChoosingWord {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerIsChoosingWord_); ok {
			return x.PlayerIsChoosingWord
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerIsDrawing() *ServerPacket_PlayerIsDrawing {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerIsDrawing_); ok {
			return x.PlayerIsDrawing
		}
	}
	return nil
}

func (x *ServerPacket) GetTurnSummary() *ServerPacket_TurnSummary {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_TurnSummary_); ok {
			return x.TurnSummary
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerGuessedTheWord() *ServerPacket_PlayerGuessedTheWord {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerGuessedTheWord_); ok {
			return x.PlayerGuessedTheWord
		}
	}
	return nil
}

func (x *ServerPacket) GetLeaderboard() *ServerPacket_LeaderBoard {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerMessage() *ServerPacket_PlayerMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerMessage_); ok {
			return x.PlayerMessage
		}
	}
	return nil
}

func (x *ServerPacket) GetPleaseChooseAWord() *ServerPacket_PleaseChooseAWord {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PleaseChooseAWord_); ok {
			return x.PleaseChooseAWord
		}
	}
	return nil
}

func (x *ServerPacket) GetInitialRoomSnapshot() *ServerPacket_InitialRoomSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_InitialRoomSnapshot_); ok {
			return x.InitialRoomSnapshot
		}
	}
	return nil
}

func (x *ServerPacket) GetYourTurnToDraw() *ServerPacket_YourTurnToDraw {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_YourTurnToDraw_); ok {
			return x.YourTurnToDraw
		}
	}
	return nil
}

func (x *ServerPacket) GetPlayerLeft() *ServerPacket_PlayerLeft {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_PlayerLeft_); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *ServerPacket) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type isServerPacket_Payload interface {
	isServerPacket_Payload()
}

type ServerPacket_DrawingData struct {
	DrawingData *DrawingData `protobuf:"bytes,1,opt,name=drawing_data,json=drawingData,proto3,oneof"`
}

type ServerPacket_PlayerJoined_ struct {
	PlayerJoined *ServerPacket_PlayerJoined `protobuf:"bytes,2,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type ServerPacket_GameStarted_ struct {
	GameStarted *ServerPacket_GameStarted `protobuf:"bytes,3,opt,name=game_started,json=gameStarted,proto3,oneof"`
}

type ServerPacket_RoundUpdate_ struct {
	RoundUpdate *ServerPacket_RoundUpdate `protobuf:"bytes,4,opt,name=round_update,json=roundUpdate,proto3,oneof"`
}

type ServerPacket_PlayerIsChoosingWord_ struct {
	PlayerIsChoosingWord *ServerPacket_PlayerIsChoosingWord `protobuf:"bytes,5,opt,name=player_is_choosing_word,json=playerIsChoosingWord,proto3,oneof"`
}

type ServerPacket_PlayerIsDrawing_ struct {
	PlayerIsDrawing *ServerPacket_PlayerIsDrawing `protobuf:"bytes,6,opt,name=player_is_drawing,json=playerIsDrawing,proto3,oneof"`
}

type ServerPacket_TurnSummary_ struct {
	TurnSummary *ServerPacket_TurnSummary `protobuf:"bytes,7,opt,name=turn_summary,json=turnSummary,proto3,oneof"`
}

type ServerPacket_PlayerGuessedTheWord_ struct {
	PlayerGuessedTheWord *ServerPacket_PlayerGuessedTheWord `protobuf:"bytes,8,opt,name=player_guessed_the_word,json=playerGuessedTheWord,proto3,oneof"`
}

type ServerPacket_Leaderboard struct {
	Leaderboard *ServerPacket_LeaderBoard `protobuf:"bytes,9,opt,name=leaderboard,proto3,oneof"`
}

type ServerPacket_PlayerMessage_ struct {
	PlayerMessage *ServerPacket_PlayerMessage `protobuf:"bytes,10,opt,name=player_message,json=playerMessage,proto3,oneof"`
}

type ServerPacket_PleaseChooseAWord_ struct {
	PleaseChooseAWord *ServerPacket_PleaseChooseAWord `protobuf:"bytes,11,opt,name=please_choose_a_word,json=pleaseChooseAWord,proto3,oneof"`
}

type ServerPacket_InitialRoomSnapshot_ struct {
	InitialRoomSnapshot *ServerPacket_InitialRoomSnapshot `protobuf:"bytes,12,opt,name=initial_room_snapshot,json=initialRoomSnapshot,proto3,oneof"`
}

type ServerPacket_YourTurnToDraw_ struct {
	YourTurnToDraw *ServerPacket_YourTurnToDraw `protobuf:"bytes,13,opt,name=your_turn_to_draw,json=yourTurnToDraw,proto3,oneof"`
}

type ServerPacket_PlayerLeft_ struct {
	PlayerLeft *ServerPacket_PlayerLeft `protobuf:"bytes,14,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

func (*ServerPacket_DrawingData) isServerPacket_Payload() {}

func (*ServerPacket_PlayerJoined_) isServerPacket_Payload() {}

func (*ServerPacket_GameStarted_) isServerPacket_Payload() {}

func (*ServerPacket_RoundUpdate_) isServerPacket_Payload() {}

func (*ServerPacket_PlayerIsChoosingWord_) isServerPacket_Payload() {}

func (*ServerPacket_PlayerIsDrawing_) isServerPacket_Payload() {}

func (*ServerPacket_TurnSummary_) isServerPacket_Payload() {}

func (*ServerPacket_PlayerGuessedTheWord_) isServerPacket_Payload() {}

func (*ServerPacket_Leaderboard) isServerPacket_Payload() {}

func (*ServerPacket_PlayerMessage_) isServerPacket_Payload() {}

func (*ServerPacket_PleaseChooseAWord_) isServerPacket_Payload() {}

func (*ServerPacket_InitialRoomSnapshot_) isServerPacket_Payload() {}

func (*ServerPacket_YourTurnToDraw_) isServerPacket_Payload() {}

func (*ServerPacket_PlayerLeft_) isServerPacket_Payload() {}

type ClientPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientPacket_DrawingData
	//	*ClientPacket_PlayerMessage_
	//	*ClientPacket_WordChoice_
	//	*ClientPacket_StartGame_
	Payload       isClientPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPacket) GetPayload() isClientPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientPacket) GetDrawingData() *DrawingData {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_DrawingData); ok {
			return x.DrawingData
		}
	}
	return nil
}

func (x *ClientPacket) GetPlayerMessage() *ClientPacket_PlayerMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_PlayerMessage_); ok {
			return x.PlayerMessage
		}
	}
	return nil
}

func (x *ClientPacket) GetWordChoice() *ClientPacket_WordChoice {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_WordChoice_); ok {
			return x.WordChoice
		}
	}
	return nil
}

func (x *ClientPacket) GetStartGame() *ClientPacket_StartGame {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_StartGame_); ok {
			return x.StartGame
		}
	}
	return nil
}

type isClientPacket_Payload interface {
	isClientPacket_Payload()
}

type ClientPacket_DrawingData struct {
	DrawingData *DrawingData `protobuf:"bytes,1,opt,name=drawing_data,json=drawingData,proto3,oneof"`
}

type ClientPacket_PlayerMessage_ struct {
	PlayerMessage *ClientPacket_PlayerMessage `protobuf:"bytes,2,opt,name=player_message,json=playerMessage,proto3,oneof"`
}

type ClientPacket_WordChoice_ struct {
	WordChoice *ClientPacket_WordChoice `protobuf:"bytes,3,opt,name=word_choice,json=wordChoice,proto3,oneof"`
}

type ClientPacket_StartGame_ struct {
	StartGame *ClientPacket_StartGame `protobuf:"bytes,5,opt,name=start_game,json=startGame,proto3,oneof"`
}

func (*ClientPacket_DrawingData) isClientPacket_Payload() {}

func (*ClientPacket_PlayerMessage_) isClientPacket_Payload() {}

func (*ClientPacket_WordChoice_) isClientPacket_Payload() {}

func (*ClientPacket_StartGame_) isClientPacket_Payload() {}

type DrawingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawingData) Reset() {
	*x = DrawingData{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawingData) ProtoMessage() {}

func (x *DrawingData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawingData.ProtoReflect.Descriptor instead.
func (*DrawingData) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DrawingData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerPacket_YourTurnToDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_YourTurnToDraw) Reset() {
	*x = ServerPacket_YourTurnToDraw{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_YourTurnToDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_YourTurnToDraw) ProtoMessage() {}

func (x *ServerPacket_YourTurnToDraw) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_YourTurnToDraw.ProtoReflect.Descriptor instead.
func (*ServerPacket_YourTurnToDraw) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServerPacket_YourTurnToDraw) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type ServerPacket_InitialRoomSnapshot struct {
	state                protoimpl.MessageState                          `protogen:"open.v1"`
	PlayersStates        []*ServerPacket_InitialRoomSnapshot_PlayerState `protobuf:"bytes,1,rep,name=players_states,json=playersStates,proto3" json:"players_states,omitempty"`
	DrawingHistory       [][]byte                                        `protobuf:"bytes,2,rep,name=drawing_history,json=drawingHistory,proto3" json:"drawing_history,omitempty"`
	CurrentDrawer        string                                          `protobuf:"bytes,3,opt,name=current_drawer,json=currentDrawer,proto3" json:"current_drawer,omitempty"`
	CurrentRound         int32                                           `protobuf:"varint,4,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	RoomId               string                                          `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	NextTick             int64                                           `protobuf:"varint,6,opt,name=next_tick,json=nextTick,proto3" json:"next_tick,omitempty"`
	ChoosingWordDuration int64                                           `protobuf:"varint,7,opt,name=choosing_word_duration,json=choosingWordDuration,proto3" json:"choosing_word_duration,omitempty"`
	DrawingDuration      int64                                           `protobuf:"varint,8,opt,name=drawing_duration,json=drawingDuration,proto3" json:"drawing_duration,omitempty"`
	CurrentPhase         int32                                           `protobuf:"varint,9,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerPacket_InitialRoomSnapshot) Reset() {
	*x = ServerPacket_InitialRoomSnapshot{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_InitialRoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_InitialRoomSnapshot) ProtoMessage() {}

func (x *ServerPacket_InitialRoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_InitialRoomSnapshot.ProtoReflect.Descriptor instead.
func (*ServerPacket_InitialRoomSnapshot) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServerPacket_InitialRoomSnapshot) GetPlayersStates() []*ServerPacket_InitialRoomSnapshot_PlayerState {
	if x != nil {
		return x.PlayersStates
	}
	return nil
}

func (x *ServerPacket_InitialRoomSnapshot) GetDrawingHistory() [][]byte {
	if x != nil {
		return x.DrawingHistory
	}
	return nil
}

func (x *ServerPacket_InitialRoomSnapshot) GetCurrentDrawer() string {
	if x != nil {
		return x.CurrentDrawer
	}
	return ""
}

func (x *ServerPacket_InitialRoomSnapshot) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *ServerPacket_InitialRoomSnapshot) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ServerPacket_InitialRoomSnapshot) GetNextTick() int64 {
	if x != nil {
		return x.NextTick
	}
	return 0
}

func (x *ServerPacket_InitialRoomSnapshot) GetChoosingWordDuration() int64 {
	if x != nil {
		return x.ChoosingWordDuration
	}
	return 0
}

func (x *ServerPacket_InitialRoomSnapshot) GetDrawingDuration() int64 {
	if x != nil {
		return x.DrawingDuration
	}
	return 0
}

func (x *ServerPacket_InitialRoomSnapshot) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

type ServerPacket_PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerJoined) Reset() {
	*x = ServerPacket_PlayerJoined{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerJoined) ProtoMessage() {}

func (x *ServerPacket_PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerJoined.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerJoined) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ServerPacket_PlayerJoined) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerPacket_PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerLeft) Reset() {
	*x = ServerPacket_PlayerLeft{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerLeft) ProtoMessage() {}

func (x *ServerPacket_PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerLeft.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerLeft) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ServerPacket_PlayerLeft) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerPacket_GameStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_GameStarted) Reset() {
	*x = ServerPacket_GameStarted{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_GameStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_GameStarted) ProtoMessage() {}

func (x *ServerPacket_GameStarted) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_GameStarted.ProtoReflect.Descriptor instead.
func (*ServerPacket_GameStarted) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 4}
}

type ServerPacket_RoundUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int64                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_RoundUpdate) Reset() {
	*x = ServerPacket_RoundUpdate{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_RoundUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_RoundUpdate) ProtoMessage() {}

func (x *ServerPacket_RoundUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_RoundUpdate.ProtoReflect.Descriptor instead.
func (*ServerPacket_RoundUpdate) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ServerPacket_RoundUpdate) GetRoundNumber() int64 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type ServerPacket_PlayerIsChoosingWord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerIsChoosingWord) Reset() {
	*x = ServerPacket_PlayerIsChoosingWord{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerIsChoosingWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerIsChoosingWord) ProtoMessage() {}

func (x *ServerPacket_PlayerIsChoosingWord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerIsChoosingWord.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerIsChoosingWord) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ServerPacket_PlayerIsChoosingWord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerPacket_PlayerIsDrawing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerIsDrawing) Reset() {
	*x = ServerPacket_PlayerIsDrawing{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerIsDrawing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerIsDrawing) ProtoMessage() {}

func (x *ServerPacket_PlayerIsDrawing) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerIsDrawing.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerIsDrawing) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ServerPacket_PlayerIsDrawing) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerPacket_TurnSummary struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	WordReveal    string                                  `protobuf:"bytes,1,opt,name=word_reveal,json=wordReveal,proto3" json:"word_reveal,omitempty"`
	Deltas        []*ServerPacket_TurnSummary_ScoreDeltas `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_TurnSummary) Reset() {
	*x = ServerPacket_TurnSummary{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_TurnSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_TurnSummary) ProtoMessage() {}

func (x *ServerPacket_TurnSummary) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_TurnSummary.ProtoReflect.Descriptor instead.
func (*ServerPacket_TurnSummary) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 8}
}

func (x *ServerPacket_TurnSummary) GetWordReveal() string {
	if x != nil {
		return x.WordReveal
	}
	return ""
}

func (x *ServerPacket_TurnSummary) GetDeltas() []*ServerPacket_TurnSummary_ScoreDeltas {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type ServerPacket_PlayerGuessedTheWord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerGuessedTheWord) Reset() {
	*x = ServerPacket_PlayerGuessedTheWord{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerGuessedTheWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerGuessedTheWord) ProtoMessage() {}

func (x *ServerPacket_PlayerGuessedTheWord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerGuessedTheWord.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerGuessedTheWord) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 9}
}

func (x *ServerPacket_PlayerGuessedTheWord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerPacket_LeaderBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_LeaderBoard) Reset() {
	*x = ServerPacket_LeaderBoard{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_LeaderBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_LeaderBoard) ProtoMessage() {}

func (x *ServerPacket_LeaderBoard) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_LeaderBoard.ProtoReflect.Descriptor instead.
func (*ServerPacket_LeaderBoard) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 10}
}

type ServerPacket_PlayerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PlayerMessage) Reset() {
	*x = ServerPacket_PlayerMessage{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PlayerMessage) ProtoMessage() {}

func (x *ServerPacket_PlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PlayerMessage.ProtoReflect.Descriptor instead.
func (*ServerPacket_PlayerMessage) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 11}
}

func (x *ServerPacket_PlayerMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ServerPacket_PlayerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerPacket_PleaseChooseAWord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []string               `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_PleaseChooseAWord) Reset() {
	*x = ServerPacket_PleaseChooseAWord{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_PleaseChooseAWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_PleaseChooseAWord) ProtoMessage() {}

func (x *ServerPacket_PleaseChooseAWord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_PleaseChooseAWord.ProtoReflect.Descriptor instead.
func (*ServerPacket_PleaseChooseAWord) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 12}
}

func (x *ServerPacket_PleaseChooseAWord) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type ServerPacket_InitialRoomSnapshot_PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	IsGuesser     bool                   `protobuf:"varint,3,opt,name=is_guesser,json=isGuesser,proto3" json:"is_guesser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) Reset() {
	*x = ServerPacket_InitialRoomSnapshot_PlayerState{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_InitialRoomSnapshot_PlayerState) ProtoMessage() {}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_InitialRoomSnapshot_PlayerState.ProtoReflect.Descriptor instead.
func (*ServerPacket_InitialRoomSnapshot_PlayerState) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ServerPacket_InitialRoomSnapshot_PlayerState) GetIsGuesser() bool {
	if x != nil {
		return x.IsGuesser
	}
	return false
}

type ServerPacket_TurnSummary_ScoreDeltas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ScoreDelta    int64                  `protobuf:"varint,2,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket_TurnSummary_ScoreDeltas) Reset() {
	*x = ServerPacket_TurnSummary_ScoreDeltas{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket_TurnSummary_ScoreDeltas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket_TurnSummary_ScoreDeltas) ProtoMessage() {}

func (x *ServerPacket_TurnSummary_ScoreDeltas) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket_TurnSummary_ScoreDeltas.ProtoReflect.Descriptor instead.
func (*ServerPacket_TurnSummary_ScoreDeltas) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{0, 8, 0}
}

func (x *ServerPacket_TurnSummary_ScoreDeltas) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerPacket_TurnSummary_ScoreDeltas) GetScoreDelta() int64 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

type ClientPacket_StartGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket_StartGame) Reset() {
	*x = ClientPacket_StartGame{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket_StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket_StartGame) ProtoMessage() {}

func (x *ClientPacket_StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket_StartGame.ProtoReflect.Descriptor instead.
func (*ClientPacket_StartGame) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{1, 0}
}

type ClientPacket_WordChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Choice        int64                  `protobuf:"varint,1,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket_WordChoice) Reset() {
	*x = ClientPacket_WordChoice{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket_WordChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket_WordChoice) ProtoMessage() {}

func (x *ClientPacket_WordChoice) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket_WordChoice.ProtoReflect.Descriptor instead.
func (*ClientPacket_WordChoice) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ClientPacket_WordChoice) GetChoice() int64 {
	if x != nil {
		return x.Choice
	}
	return 0
}

type ClientPacket_PlayerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket_PlayerMessage) Reset() {
	*x = ClientPacket_PlayerMessage{}
	mi := &file_domain_protobuf_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket_PlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket_PlayerMessage) ProtoMessage() {}

func (x *ClientPacket_PlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_domain_protobuf_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket_PlayerMessage.ProtoReflect.Descriptor instead.
func (*ClientPacket_PlayerMessage) Descriptor() ([]byte, []int) {
	return file_domain_protobuf_protocol_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ClientPacket_PlayerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_domain_protobuf_protocol_proto protoreflect.FileDescriptor

const file_domain_protobuf_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/protobuf/protocol.proto\x12\bprotobuf\"\xd3\x12\n" +
	"\fServerPacket\x12:\n" +
	"\fdrawing_data\x18\x01 \x01(\v2\x15.protobuf.DrawingDataH\x00R\vdrawingData\x12J\n" +
	"\rplayer_joined\x18\x02 \x01(\v2#.protobuf.ServerPacket.PlayerJoinedH\x00R\fplayerJoined\x12G\n" +
	"\fgame_started\x18\x03 \x01(\v2\".protobuf.ServerPacket.GameStartedH\x00R\vgameStarted\x12G\n" +
	"\fround_update\x18\x04 \x01(\v2\".protobuf.ServerPacket.RoundUpdateH\x00R\vroundUpdate\x12d\n" +
	"\x17player_is_choosing_word\x18\x05 \x01(\v2+.protobuf.ServerPacket.PlayerIsChoosingWordH\x00R\x14playerIsChoosingWord\x12T\n" +
	"\x11player_is_drawing\x18\x06 \x01(\v2&.protobuf.ServerPacket.PlayerIsDrawingH\x00R\x0fplayerIsDrawing\x12G\n" +
	"\fturn_summary\x18\a \x01(\v2\".protobuf.ServerPacket.TurnSummaryH\x00R\vturnSummary\x12d\n" +
	"\x17player_guessed_the_word\x18\b \x01(\v2+.protobuf.ServerPacket.PlayerGuessedTheWordH\x00R\x14playerGuessedTheWord\x12F\n" +
	"\vleaderboard\x18\t \x01(\v2\".protobuf.ServerPacket.LeaderBoardH\x00R\vleaderboard\x12M\n" +
	"\x0eplayer_message\x18\n" +
	" \x01(\v2$.protobuf.ServerPacket.PlayerMessageH\x00R\rplayerMessage\x12[\n" +
	"\x14please_choose_a_word\x18\v \x01(\v2(.protobuf.ServerPacket.PleaseChooseAWordH\x00R\x11pleaseChooseAWord\x12`\n" +
	"\x15initial_room_snapshot\x18\f \x01(\v2*.protobuf.ServerPacket.InitialRoomSnapshotH\x00R\x13initialRoomSnapshot\x12R\n" +
	"\x11your_turn_to_draw\x18\r \x01(\v2%.protobuf.ServerPacket.YourTurnToDrawH\x00R\x0eyourTurnToDraw\x12D\n" +
	"\vplayer_left\x18\x0e \x01(\v2!.protobuf.ServerPacket.PlayerLeftH\x00R\n" +
	"playerLeft\x12)\n" +
	"\x10server_timestamp\x18\x10 \x01(\x03R\x0fserverTimestamp\x1a$\n" +
	"\x0eYourTurnToDraw\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x1a\x85\x04\n" +
	"\x13InitialRoomSnapshot\x12]\n" +
	"\x0eplayers_states\x18\x01 \x03(\v26.protobuf.ServerPacket.InitialRoomSnapshot.PlayerStateR\rplayersStates\x12'\n" +
	"\x0fdrawing_history\x18\x02 \x03(\fR\x0edrawingHistory\x12%\n" +
	"\x0ecurrent_drawer\x18\x03 \x01(\tR\rcurrentDrawer\x12#\n" +
	"\rcurrent_round\x18\x04 \x01(\x05R\fcurrentRound\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tnext_tick\x18\x06 \x01(\x03R\bnextTick\x124\n" +
	"\x16choosing_word_duration\x18\a \x01(\x03R\x14choosingWordDuration\x12)\n" +
	"\x10drawing_duration\x18\b \x01(\x03R\x0fdrawingDuration\x12#\n" +
	"\rcurrent_phase\x18\t \x01(\x05R\fcurrentPhase\x1a^\n" +
	"\vPlayerState\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x1d\n" +
	"\n" +
	"is_guesser\x18\x03 \x01(\bR\tisGuesser\x1a*\n" +
	"\fPlayerJoined\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1a(\n" +
	"\n" +
	"PlayerLeft\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1a\r\n" +
	"\vGameStarted\x1a0\n" +
	"\vRoundUpdate\x12!\n" +
	"\fround_number\x18\x01 \x01(\x03R\vroundNumber\x1a2\n" +
	"\x14PlayerIsChoosingWord\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1a-\n" +
	"\x0fPlayerIsDrawing\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1a\xc2\x01\n" +
	"\vTurnSummary\x12\x1f\n" +
	"\vword_reveal\x18\x01 \x01(\tR\n" +
	"wordReveal\x12F\n" +
	"\x06deltas\x18\x02 \x03(\v2..protobuf.ServerPacket.TurnSummary.ScoreDeltasR\x06deltas\x1aJ\n" +
	"\vScoreDeltas\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vscore_delta\x18\x02 \x01(\x03R\n" +
	"scoreDelta\x1a2\n" +
	"\x14PlayerGuessedTheWord\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1a\r\n" +
	"\vLeaderBoard\x1a=\n" +
	"\rPlayerMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1a)\n" +
	"\x11PleaseChooseAWord\x12\x14\n" +
	"\x05words\x18\x01 \x03(\tR\x05wordsB\t\n" +
	"\apayload\"\x8b\x03\n" +
	"\fClientPacket\x12:\n" +
	"\fdrawing_data\x18\x01 \x01(\v2\x15.protobuf.DrawingDataH\x00R\vdrawingData\x12M\n" +
	"\x0eplayer_message\x18\x02 \x01(\v2$.protobuf.ClientPacket.PlayerMessageH\x00R\rplayerMessage\x12D\n" +
	"\vword_choice\x18\x03 \x01(\v2!.protobuf.ClientPacket.WordChoiceH\x00R\n" +
	"wordChoice\x12A\n" +
	"\n" +
	"start_game\x18\x05 \x01(\v2 .protobuf.ClientPacket.StartGameH\x00R\tstartGame\x1a\v\n" +
	"\tStartGame\x1a$\n" +
	"\n" +
	"WordChoice\x12\x16\n" +
	"\x06choice\x18\x01 \x01(\x03R\x06choice\x1a)\n" +
	"\rPlayerMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\t\n" +
	"\apayload\"!\n" +
	"\vDrawingData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\x1eZ\x1capi/domain/protobuf;protobufb\x06proto3"

var (
	file_domain_protobuf_protocol_proto_rawDescOnce sync.Once
	file_domain_protobuf_protocol_proto_rawDescData []byte
)

func file_domain_protobuf_protocol_proto_rawDescGZIP() []byte {
	file_domain_protobuf_protocol_proto_rawDescOnce.Do(func() {
		file_domain_protobuf_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_protobuf_protocol_proto_rawDesc), len(file_domain_protobuf_protocol_proto_rawDesc)))
	})
	return file_domain_protobuf_protocol_proto_rawDescData
}

var file_domain_protobuf_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_domain_protobuf_protocol_proto_goTypes = []any{
	(*ServerPacket)(nil),                                 // 0: protobuf.ServerPacket
	(*ClientPacket)(nil),                                 // 1: protobuf.ClientPacket
	(*DrawingData)(nil),                                  // 2: protobuf.DrawingData
	(*ServerPacket_YourTurnToDraw)(nil),                  // 3: protobuf.ServerPacket.YourTurnToDraw
	(*ServerPacket_InitialRoomSnapshot)(nil),             // 4: protobuf.ServerPacket.InitialRoomSnapshot
	(*ServerPacket_PlayerJoined)(nil),                    // 5: protobuf.ServerPacket.PlayerJoined
	(*ServerPacket_PlayerLeft)(nil),                      // 6: protobuf.ServerPacket.PlayerLeft
	(*ServerPacket_GameStarted)(nil),                     // 7: protobuf.ServerPacket.GameStarted
	(*ServerPacket_RoundUpdate)(nil),                     // 8: protobuf.ServerPacket.RoundUpdate
	(*ServerPacket_PlayerIsChoosingWord)(nil),            // 9: protobuf.ServerPacket.PlayerIsChoosingWord
	(*ServerPacket_PlayerIsDrawing)(nil),                 // 10: protobuf.ServerPacket.PlayerIsDrawing
	(*ServerPacket_TurnSummary)(nil),                     // 11: protobuf.ServerPacket.TurnSummary
	(*ServerPacket_PlayerGuessedTheWord)(nil),            // 12: protobuf.ServerPacket.PlayerGuessedTheWord
	(*ServerPacket_LeaderBoard)(nil),                     // 13: protobuf.ServerPacket.LeaderBoard
	(*ServerPacket_PlayerMessage)(nil),                   // 14: protobuf.ServerPacket.PlayerMessage
	(*ServerPacket_PleaseChooseAWord)(nil),               // 15: protobuf.ServerPacket.PleaseChooseAWord
	(*ServerPacket_InitialRoomSnapshot_PlayerState)(nil), // 16: protobuf.ServerPacket.InitialRoomSnapshot.PlayerState
	(*ServerPacket_TurnSummary_ScoreDeltas)(nil),         // 17: protobuf.ServerPacket.TurnSummary.ScoreDeltas
	(*ClientPacket_StartGame)(nil),                       // 18: protobuf.ClientPacket.StartGame
	(*ClientPacket_WordChoice)(nil),                      // 19: protobuf.ClientPacket.WordChoice
	(*ClientPacket_PlayerMessage)(nil),                   // 20: protobuf.ClientPacket.PlayerMessage
}
var file_domain_protobuf_protocol_proto_depIdxs = []int32{
	2,  // 0: protobuf.ServerPacket.drawing_data:type_name -> protobuf.DrawingData
	5,  // 1: protobuf.ServerPacket.player_joined:type_name -> protobuf.ServerPacket.PlayerJoined
	7,  // 2: protobuf.ServerPacket.game_started:type_name -> protobuf.ServerPacket.GameStarted
	8,  // 3: protobuf.ServerPacket.round_update:type_name -> protobuf.ServerPacket.RoundUpdate
	9,  // 4: protobuf.ServerPacket.player_is_choosing_word:type_name -> protobuf.ServerPacket.PlayerIsChoosingWord
	10, // 5: protobuf.ServerPacket.player_is_drawing:type_name -> protobuf.ServerPacket.PlayerIsDrawing
	11, // 6: protobuf.ServerPacket.turn_summary:type_name -> protobuf.ServerPacket.TurnSummary
	12, // 7: protobuf.ServerPacket.player_guessed_the_word:type_name -> protobuf.ServerPacket.PlayerGuessedTheWord
	13, // 8: protobuf.ServerPacket.leaderboard:type_name -> protobuf.ServerPacket.LeaderBoard
	14, // 9: protobuf.ServerPacket.player_message:type_name -> protobuf.ServerPacket.PlayerMessage
	15, // 10: protobuf.ServerPacket.please_choose_a_word:type_name -> protobuf.ServerPacket.PleaseChooseAWord
	4,  // 11: protobuf.ServerPacket.initial_room_snapshot:type_name -> protobuf.ServerPacket.InitialRoomSnapshot
	3,  // 12: protobuf.ServerPacket.your_turn_to_draw:type_name -> protobuf.ServerPacket.YourTurnToDraw
	6,  // 13: protobuf.ServerPacket.player_left:type_name -> protobuf.ServerPacket.PlayerLeft
	2,  // 14: protobuf.ClientPacket.drawing_data:type_name -> protobuf.DrawingData
	20, // 15: protobuf.ClientPacket.player_message:type_name -> protobuf.ClientPacket.PlayerMessage
	19, // 16: protobuf.ClientPacket.word_choice:type_name -> protobuf.ClientPacket.WordChoice
	18, // 17: protobuf.ClientPacket.start_game:type_name -> protobuf.ClientPacket.StartGame
	16, // 18: protobuf.ServerPacket.InitialRoomSnapshot.players_states:type_name -> protobuf.ServerPacket.InitialRoomSnapshot.PlayerState
	17, // 19: protobuf.ServerPacket.TurnSummary.deltas:type_name -> protobuf.ServerPacket.TurnSummary.ScoreDeltas
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_domain_protobuf_protocol_proto_init() }
func file_domain_protobuf_protocol_proto_init() {
	if File_domain_protobuf_protocol_proto != nil {
		return
	}
	file_domain_protobuf_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerPacket_DrawingData)(nil),
		(*ServerPacket_PlayerJoined_)(nil),
		(*ServerPacket_GameStarted_)(nil),
		(*ServerPacket_RoundUpdate_)(nil),
		(*ServerPacket_PlayerIsChoosingWord_)(nil),
		(*ServerPacket_PlayerIsDrawing_)(nil),
		(*ServerPacket_TurnSummary_)(nil),
		(*ServerPacket_PlayerGuessedTheWord_)(nil),
		(*ServerPacket_Leaderboard)(nil),
		(*ServerPacket_PlayerMessage_)(nil),
		(*ServerPacket_PleaseChooseAWord_)(nil),
		(*ServerPacket_InitialRoomSnapshot_)(nil),
		(*ServerPacket_YourTurnToDraw_)(nil),
		(*ServerPacket_PlayerLeft_)(nil),
	}
	file_domain_protobuf_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientPacket_DrawingData)(nil),
		(*ClientPacket_PlayerMessage_)(nil),
		(*ClientPacket_WordChoice_)(nil),
		(*ClientPacket_StartGame_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_protobuf_protocol_proto_rawDesc), len(file_domain_protobuf_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_protobuf_protocol_proto_goTypes,
		DependencyIndexes: file_domain_protobuf_protocol_proto_depIdxs,
		MessageInfos:      file_domain_protobuf_protocol_proto_msgTypes,
	}.Build()
	File_domain_protobuf_protocol_proto = out.File
	file_domain_protobuf_protocol_proto_goTypes = nil
	file_domain_protobuf_protocol_proto_depIdxs = nil
}
